ingress:
  - https://tiltakspenger-saksbehandler.ansatt.dev.nav.no
replyURLs:
  - https://tiltakspenger-saksbehandler.ansatt.dev.nav.no/oauth2/callback
tenant: trygdeetaten.no
ROLE_SAKSBEHANDLER: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
cluster: dev-gcp
envs:
  - name: TILTAKSPENGER_SAKSBEHANDLING_API_URL
    value: http://tiltakspenger-saksbehandling-api
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
  - name: SAKSBEHANDLING_API_SCOPE
    value: api://dev-gcp.tpts.tiltakspenger-saksbehandling-api/.default
replicas: 1
