ingress:
  - https://tiltakspenger-saksbehandler.intern.dev.nav.no
replyURLs:
  - https://tiltakspenger-saksbehandler.intern.dev.nav.no/oauth2/callback
tenant: trygdeetaten.no
ROLE_SAKSBEHANDLER: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
cluster: dev-gcp
envs:
  - name: TILTAKSPENGER_VEDTAK_URL
    value: http://tiltakspenger-vedtak
  - name: TILTAKSPENGER_MELDEKORT_URL
    value: http://tiltakspenger-meldekort-api
  - name: TILTAKSPENGER_UTBETALING_URL
    value: http://tiltakspenger-utbetaling
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
  - name: SCOPE
    value: eafda703-c821-44de-990c-950dec1ad22f
