ingress:
  - https://tiltakspenger-saksbehandler.intern.nav.no
  - https://tiltakspenger-saksbehandler.ansatt.nav.no
replyURLs:
  - https://tiltakspenger-saksbehandler.intern.nav.no/oauth2/callback
tenant: nav.no
azure:
  groups:
    - name: ROLE_SAKSBEHANDLER
      id: 6c6ce2e8-b2e2-4c4b-8194-215c8e27a5c7
    - name: ROLE_BESLUTTER
      id: de518927-f657-4f37-9a64-14fdfd968dd2
    - name: ROLE_DRIFT
      id: 0405ed09-1248-47f7-a6e3-e998bc90feca
cluster: prod-gcp
envs:
  - name: TILTAKSPENGER_SAKSBEHANDLING_API_URL
    value: http://tiltakspenger-saksbehandling-api
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/oauth2/v2.0/token
  - name: SAKSBEHANDLING_API_SCOPE
    value: api://prod-gcp.tpts.tiltakspenger-saksbehandling-api/.default
replicas: 2
