apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-saksbehandler
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - {{ ingress }}
  replicas:
    min: 1
    max: 1
  env:
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  {{#if tenant}}
    azure:
      sidecar:
        enabled: true
        autoLogin: true
        openid.provider: "azure"
        errorPath: ""
      application:
        enabled: true
        tenant: {{ tenant }}
        claims:
          groups:
            - id: {{ ROLE_SAKSBEHANDLER }}
          extra:
            - "NAVident"
        {{#if replyUrls}}
          replyURLs:
          {{#each replyUrls}}
            - {{ this }}
          {{/each}}
        {{/if}}
  {{/if}}