apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-saksbehandler
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - {{ ingress }}
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  secureLogs:
    enabled: true
  env:
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
          cluster: {{ cluster }}
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      tenant: {{ tenant }}
      claims:
        groups:
          - id: {{ ROLE_SAKSBEHANDLER }}
        extra:
          - "NAVident"
      {{#if replyUrls}}
        replyURLs:
        {{#each replyUrls}}
          - {{ this }}
        {{/each}}
      {{/if}}
