apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-saksbehandler
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - https://tiltakspenger-saksbehandler.labs.nais.io
  replicas:
    min: 1
    max: 1
  env:
    - name: TILTAKSPENGER_VEDTAK_URL
      value: https://tiltakspenger-vedtak.labs.nais.io